Document: ndlrdeposit
Title: Debian ndlrdeposit Manual
Author: <insert document author here>
Abstract: This manual describes what ndlrdeposit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ndlrdeposit/ndlrdeposit.sgml.gz

Format: postscript
Files: /usr/share/doc/ndlrdeposit/ndlrdeposit.ps.gz

Format: text
Files: /usr/share/doc/ndlrdeposit/ndlrdeposit.text.gz

Format: HTML
Index: /usr/share/doc/ndlrdeposit/html/index.html
Files: /usr/share/doc/ndlrdeposit/html/*.html
